#!/bin/bash
# Turns off all known external screens and enables to HiDPI.

echo "Xft.dpi: 192" | xrdb -merge
i3-msg restart
xrandr \
 --output DP-3-1 --off --output DP-3-2 --off \
 --output eDP-1 \
  --mode 3840x2400 \
  --primary
