#!/bin/sh

LOCK_IMAGE=/tmp/i3lock.png

scrot ${LOCK_IMAGE}
convert ${LOCK_IMAGE}  -blur 5x2 ${LOCK_IMAGE}

revert() {
  xset dpms 0 0 0
}

trap revert HUP INT TERM

xset +dpms dpms 5 5 5
i3lock -n -i ${LOCK_IMAGE}
rm ${LOCK_IMAGE}
revert
