#!/bin/bash
# Switches laptop screen to 1080p and turns on external screens.

echo "Xft.dpi: 96" | xrdb -merge
i3-msg restart
xrandr \
  --output eDP-1 \
    --mode 1920x1200 \
    --primary \
  --output DP-3-1 \
    --auto \
    --right-of eDP-1 \
  --output DP-3-2 \
    --auto \
    --right-of DP-3-1 \
    --rotate left
